Repository PrograMemo-Groom/900pro-fe, pull requests merged in 2025-04, with the labels that each got.

#8 [프로젝트 기본 설정]
  index.html
  package-lock.json
  package.json
  src/App.css
  src/App.tsx
  src/assets/fonts/Inter-VariableFont_opsz,wght.ttf
  src/assets/fonts/LeagueSpartan-Bold.ttf
  src/assets/fonts/SairaCondensed-Medium.ttf
  src/css/common/_global.scss
  src/css/login/Login.module.scss
  src/index.css
  src/index.scss
  src/main.tsx
  src/pages/login/Login.interface.ts
  src/pages/login/Login.tsx
  src/router/index.tsx
  src/store/api/ApiConfig.ts
  src/store/auth/api.ts
  src/store/auth/endpoints.ts
  src/store/auth/slices.ts
  src/store/auth/thunks.ts
  src/store/index.ts
  tsconfig.app.json
  tsconfig.json
  vite.config.ts
Labels: 리팩토링, 버그

#10 [Feature/chat UI] 전체 css 수정 및 채팅 기본 구조 생성
  src/css/history/Chat.module.scss
  src/index.scss
  src/pages/history/Chat.tsx
  src/pages/history/TeamViewer.tsx
  src/router/index.tsx
Labels: 기능추가

#11 [Feature/chat UI] 채팅창 UI 제작
  src/css/history/Chat.module.scss
  src/pages/history/Chat.tsx
Labels: 기능추가

#15 [Feature/chat UI] 채팅창 리팩토링
  src/css/history/BubbleChatbot.module.scss
  src/css/history/BubbleLeft.module.scss
  src/css/history/BubbleMe.module.scss
  src/css/history/Chat.module.scss
  src/pages/history/Chat.tsx
  src/pages/history/ChatInput.tsx
  src/pages/history/ChatLog.tsx
  src/pages/history/chatbubble/BubbleChatbot.tsx
  src/pages/history/chatbubble/BubbleLeft.tsx
  src/pages/history/chatbubble/BubbleMe.tsx
  src/pages/history/chatbubble/DateDivider.tsx
  src/pages/history/chatbubble/formatTime.ts
  src/pages/history/chatbubble/index.ts
  src/pages/history/data/ChatDummy.ts
Labels: 기능추가, 리팩토링

#20 publish 작업 진행중
  src/assets/Search.svg
  src/assets/burger.svg
  src/css/common/_global.scss
  src/css/login/Auth.module.scss
  src/css/main/Layout.module.scss
  src/pages/common/Header.tsx
  src/pages/common/Landing.tsx
  src/pages/login/Login.interface.ts
  src/pages/login/Login.tsx
  src/pages/main/MainNoTeam.interface.ts
  src/pages/main/MainNoTeam.tsx
  src/pages/main/TeamDialog/TeamCreate.tsx
  src/pages/main/TeamDialog/TeamDetail.tsx
  src/pages/main/component/FilterOrder.tsx
  src/pages/main/component/FilterQuestion.tsx
  src/pages/main/component/SearchBox.tsx
  src/pages/main/component/TeamHeader.tsx
  src/pages/resetPassword/ResetPassword.interface.ts
  src/pages/resetPassword/ResetPassword.tsx
  src/pages/signUp/SignUp.interfase.ts
  src/pages/signUp/SignUp.tsx
  src/router/index.tsx
Labels: 기능추가

#24 [Feature/chat UI] 팀원 코드 컴포넌트 UI
  package-lock.json
  package.json
  src/api/stompClient.ts
  src/css/history/BubbleChatbot.module.scss
  src/css/history/BubbleMe.module.scss
  src/css/history/Chat.module.scss
  src/css/history/ChatInput.module.scss
  src/css/history/ChatPage.module.scss
  src/css/history/TeamView/TeamCode.module.scss
  src/css/history/TeamView/TeamProb.module.scss
  src/css/history/TeamView/TeamView.module.scss
  src/pages/history/Chat.tsx
  src/pages/history/ChatInput.tsx
  src/pages/history/ChatLog.tsx
  src/pages/history/ChatPage.tsx
  src/pages/history/ChatTest.tsx
  src/pages/history/TeamCode.tsx
  src/pages/history/TeamProb.tsx
  src/pages/history/TeamViewer.tsx
  src/pages/history/chatbubble/BubbleChatbot.tsx
  src/pages/history/chatbubble/BubbleMe.tsx
  src/pages/history/types/Chat.ts
  src/router/index.tsx
  src/store/history/uiSlice.ts
  src/store/index.ts
  vite.config.ts
Labels: 기능추가

#36 [Feature/chat soket connect] 문제 불러오기
  src/api/historyApi.ts
  src/css/teamain/TeamMain.module.scss
  src/pages/history/Chat.tsx
  src/pages/history/ChatLog.tsx
  src/pages/history/ChatTest.tsx
  src/pages/history/TeamProb.tsx
  src/pages/history/TeamViewer.tsx
  src/pages/history/chatbubble/BubbleChatbot.tsx
  src/pages/teamain/TeamMain.tsx
  src/router/index.tsx
  src/store/history/problemSlice.ts
  src/store/index.ts
  vite.config.ts
Labels: 기능추가

#39 [Feature/chat soket connect] 채팅 토큰, 아이디 변수 설정 및 팀 메인페이지 UI
  src/api/stompClient.ts
  src/assets/hamb.svg
  src/css/common/_global.scss
  src/css/teamain/TeamMain.module.scss
  src/pages/history/Chat.tsx
  src/pages/history/ChatLog.tsx
  src/pages/teamain/TeamMain.tsx
  vite.config.ts
Labels: 기능추가

#43 [Feat] 웨이팅룸 타이머 - 자동 화면 이동 및 테스트 아이디 리덕스 저장
  src/css/common/_global.scss
  src/css/history/ChatPage.module.scss
  src/css/main/CreateModal.module.scss
  src/css/main/Layout.module.scss
  src/pages/history/Chat.tsx
  src/pages/history/ChatLog.tsx
  src/pages/history/ChatPage.tsx
  src/pages/main/MainNoTeam.tsx
  src/pages/main/TeamDialog/TeamCreate.tsx
  src/pages/main/TeamDialog/TeamDetail.tsx
  src/pages/main/component/TeamHeader.tsx
  src/pages/teamain/TeamMain copy.tsx
  src/pages/teamain/TeamMain.tsx
  src/pages/waitingRoom/Timer.tsx
  src/pages/waitingRoom/WaitingRoom.tsx
  src/store/api/ApiConfig.ts
  src/store/team/teamainSlice.ts
  vite.config.ts
Labels: 기능추가, 리팩토링
